module.exports = {
    CLIENTES: 'CLIE01',
    COMPRAS: 'COMPC01',
    COMPRA_PARTIDAS: 'PAR_COMPC01',
    CONCEPTOS:'CONP01',
    FACTURAS:'FACTF01',
    FACTURA_PARTIDAS:'PAR_FACTF01',
    FOLIOS: 'FOLCXP01',
    INVENTARIOS: 'INVE01',
    INVENTARIO_CAMPOLIBRE: 'INVE_CLIB01',
    PAGOS: 'PAGA_M01',
    PROVEEDORES: 'PROV01',
    LIMIT: "FIRST 100"
}